### ISSUE TITLE
Issue with building the project

### ISSUE THREAD

**Issue by RupertWalsh** [Azure/azure-iot-device-ecosystem#119]
Trying to build the solution in section 3.1 step 4 using Eclipse Workspace on Windows, I get 2 build errors to do with the AzureIOTSDK:

1. fatal error: opening dependency file Middlewares/AzureIOTSDK/azure-c-shared-utility/adapters/agenttime_STM32Cube.d: No such file or directory	agenttime_STM32Cube.c	/STM32F4xx-Nucleo/Middlewares/AzureIOTSDK/azure-c-shared-utility/adapters	line 46	C/C++ Problem
2. make: *** [Middlewares/AzureIOTSDK/azure-c-shared-utility/adapters/agenttime_STM32Cube.o] Error 1	STM32F4xx-Nucleo		 	C/C++ Problem

Anyone else have this problem or have a workaround?

**Comment by matteofumagalli1275** [comment]
Hi,

Could you move the project to a directory closer to the drive root? Like C:/Test.

I got a very similar error with other stm32 eclipse projects, it seems to be an issue with the path getting too long during the build.

If you still get the issue can you tell me which project are you trying to build?

**Comment by RupertWalsh** [comment]
Thanks Matteo,

I re-installed the AzureIOT SDK (version 3.0 from the RushUp site directly) in a directory closer to the root and it worked. Thanks for your help!
