### ISSUE TITLE
Need to run dos2unix on iothub-explorer after install

### ISSUE THREAD

**Issue by sethgilchrist** [Azure/azure-iot-device-ecosystem#12]
After running 
`sudo npm installl -g iothub-explorer`
I get the error 
`env: node\r: No such file or directory`
if I try to login to my iothub.

This appears to be a line ending problem with the fact that the package was written in dos-based evn and I'm running Mac OS.

**Comment by sethgilchrist** [comment]
This can be fixed with
`$ brew install dos2unix`
`$ sudo dos2unix /usr/local/lib/node_modules/iothub-explorer/iothub-explorer.js`

**Comment by tameraw** [comment]
@sethgilchrist - Thanks for reporting this issue.
If this is still a problem, please file it under the [iothub-explorer repo](https://github.com/Azure/iothub-explorer).
Regards.
