### ISSUE TITLE
Wrong device detected, check the board connected

### ISSUE THREAD

**Issue by jimoneil** [Azure/azure-iot-device-ecosystem#237]
I'm getting this error when trying to run against a Cloud JAM STM32L476RG that was provided during some Microsoft partner training for IoT Central, the board documentation says it is the "production grade board of the FP-CLD-AZURE1 function pack".  Please advise if there is some configuration or code change required.

**Comment by 9lash** [comment]
Sorry this code was written specifically for BytePoster Master Kit. https://catalog.azureiotsolutions.com/details?title=BytePoster-Master-Kit&source=null
