### ISSUE TITLE
fatal error: azure_c_shared_utility/xlogging.h: No such file or directory 

### ISSUE THREAD

**Issue by ninhvuonglinh** [Azure/azure-iot-device-ecosystem#300]
Following instruction at the link: https://github.com/Azure/azure-iot-device-ecosystem/blob/master/get_started/iot-hub-raspberry-pi-kit-c-get-started.md
Step *Build the sample application by running the following command:*
running command 
`cmake . && make`

I'm getting the following error:
fatal error: azure_c_shared_utility/xlogging.h: No such file or directory

Details - sorry for the long content.

`
pi@raspberrypi:~ $ sudo apt-get install cmake gcc g++
Reading package lists... Done
Building dependency tree
Reading state information... Done
g++ is already the newest version (4:6.3.0-4).
g++ set to manually installed.
gcc is already the newest version (4:6.3.0-4).
gcc set to manually installed.
Suggested packages:
  codeblocks eclipse ninja-build
The following NEW packages will be installed:
  cmake cmake-data libjsoncpp1
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,685 kB of archives.
After this operation, 19.0 MB of additional disk space will be used.
Get:1 http://rpi.vietidc.com/raspbian stretch/main armhf cmake-data all 3.7.2-1                                                                                                                 [1,216 kB]
Get:2 http://rpi.vietidc.com/raspbian stretch/main armhf libjsoncpp1 armhf 1.7.4                                                                                                                -3 [66.2 kB]
Get:3 http://rpi.vietidc.com/raspbian stretch/main armhf cmake armhf 3.7.2-1 [2,                                                                                                                402 kB]
Fetched 3,685 kB in 1min 1s (60.3 kB/s)
Selecting previously unselected package cmake-data.
(Reading database ... 122983 files and directories currently installed.)
Preparing to unpack .../cmake-data_3.7.2-1_all.deb ...
Unpacking cmake-data (3.7.2-1) ...
Selecting previously unselected package libjsoncpp1:armhf.
Preparing to unpack .../libjsoncpp1_1.7.4-3_armhf.deb ...
Unpacking libjsoncpp1:armhf (1.7.4-3) ...
Selecting previously unselected package cmake.
Preparing to unpack .../cmake_3.7.2-1_armhf.deb ...
Unpacking cmake (3.7.2-1) ...
Setting up cmake-data (3.7.2-1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libjsoncpp1:armhf (1.7.4-3) ...
Setting up cmake (3.7.2-1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
pi@raspberrypi:~ $ sudo apt-get update
Get:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian stretch/main armhf Packages [1                                                                                                                1.7 MB]
Get:4 http://archive.raspberrypi.org/debian stretch/main armhf Packages [145 kB]
Get:5 http://archive.raspberrypi.org/debian stretch/ui armhf Packages [28.2 kB]
Get:6 http://mirrordirector.raspbian.org/raspbian stretch/contrib armhf Packages                                                                                                                 [56.8 kB]
Get:7 http://mirrordirector.raspbian.org/raspbian stretch/non-free armhf Package                                                                                                                s [95.2 kB]
Fetched 12.0 MB in 3min 25s (58.6 kB/s)
Reading package lists... Done
pi@raspberrypi:~ $ grep -q -F 'deb http://ppa.launchpad.net/aziotsdklinux/ppa-az                                                                                                                ureiot/ubuntu vivid main' /etc/apt/sources.list || sudo sh -c "echo 'deb http://                                                                                                                ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid main' >> /etc/apt/sour                                                                                                                ces.list"
pi@raspberrypi:~ $ grep -q -F 'deb-src http://ppa.launchpad.net/aziotsdklinux/pp                                                                                                                a-azureiot/ubuntu vivid main' /etc/apt/sources.list || sudo sh -c "echo 'deb-src                                                                                                                 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid main' >> /etc/                                                                                                                apt/sources.list"
pi@raspberrypi:~ $ sudo apt-get install dirmngr
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  pinentry-gnome3 tor
The following NEW packages will be installed:
  dirmngr
0 upgraded, 1 newly installed, 0 to remove and 219 not upgraded.
Need to get 546 kB of archives.
After this operation, 963 kB of additional disk space will be used.
Get:1 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf dirmngr arm                                                                                                                hf 2.1.18-8~deb9u1 [546 kB]
Fetched 546 kB in 8s (62.2 kB/s)
Selecting previously unselected package dirmngr.
(Reading database ... 125175 files and directories currently installed.)
Preparing to unpack .../dirmngr_2.1.18-8~deb9u1_armhf.deb ...
Unpacking dirmngr (2.1.18-8~deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up dirmngr (2.1.18-8~deb9u1) ...
pi@raspberrypi:~ $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys                                                                                                                 FDA6A393E4C2257F
Executing: /tmp/apt-key-gpghome.lDyUQrLVQw/gpg.1.sh --keyserver keyserver.ubuntu                                                                                                                .com --recv-keys FDA6A393E4C2257F
gpg: key FDA6A393E4C2257F: public key "Launchpad PPA for Azureiotsdk Team" impor                                                                                                                ted
gpg: Total number processed: 1
gpg:               imported: 1
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Get:2 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid InRelease                                                                                                                 [16.0 kB]
Hit:3 http://archive.raspberrypi.org/debian stretch InRelease
Get:4 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main Sour                                                                                                                ces [1,593 B]
Get:5 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armh                                                                                                                f Packages [1,673 B]
Get:6 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main Tran                                                                                                                slation-en [1,085 B]
Fetched 20.3 kB in 6s (3,172 B/s)
Reading package lists... Done
pi@raspberrypi:~ $ sudo apt-get install -y azure-iot-sdk-c-dev cmake
Reading package lists... Done
Building dependency tree
Reading state information... Done
cmake is already the newest version (3.7.2-1).
The following additional packages will be installed:
  azure-c-shared-util-dev azure-c-shared-util-lib azure-iot-sdk-c-lib
  azure-uamqp-c-dev azure-uamqp-c-lib azure-umqtt-c-dev azure-umqtt-c-lib curl
  libcurl3 libcurl4-openssl-dev libssl-dev libssl-doc libssl1.1 libuuid1
  uuid-dev
Suggested packages:
  libcurl4-doc libcurl3-dbg libidn11-dev libkrb5-dev libldap2-dev librtmp-dev
  libssh2-1-dev libssl1.0-dev | libssl-dev
Recommended packages:
  uuid-runtime
The following NEW packages will be installed:
  azure-c-shared-util-dev azure-c-shared-util-lib azure-iot-sdk-c-dev
  azure-iot-sdk-c-lib azure-uamqp-c-dev azure-uamqp-c-lib azure-umqtt-c-dev
  azure-umqtt-c-lib libcurl4-openssl-dev libssl-dev libssl-doc uuid-dev
The following packages will be upgraded:
  curl libcurl3 libssl1.1 libuuid1
4 upgraded, 12 newly installed, 0 to remove and 215 not upgraded.
Need to get 5,389 kB of archives.
After this operation, 14.5 MB of additional disk space will be used.
Get:2 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armh                                                                                                                f azure-c-shared-util-lib armhf 0.1.0-53vivid [76.9 kB]
Get:1 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf libuuid1 ar                                                                                                                mhf 2.29.2-1+deb9u1 [69.7 kB]
Get:3 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf libssl1.1 a                                                                                                                rmhf 1.1.0f-3+deb9u2 [1,105 kB]
Get:5 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armh                                                                                                                f azure-c-shared-util-dev armhf 0.1.0-53vivid [49.6 kB]
Get:11 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armhf azure-uamqp-c-lib armhf 0.1.0-58vivid [92.5 kB]
Get:4 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf uuid-dev armhf 2.29.2-1+deb9u1 [83.2 kB]
Get:6 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf libssl-dev armhf 1.1.0f-3+deb9u2 [1,370 kB]
Get:12 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armhf azure-uamqp-c-dev armhf 0.1.0-58vivid [18.0 kB]
Get:13 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armhf azure-umqtt-c-lib armhf 0.1.0-48vivid [14.3 kB]
Get:14 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armhf azure-umqtt-c-dev armhf 0.1.0-48vivid [5,360 B]
Get:7 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf curl armhf 7.52.1-5+deb9u5 [220 kB]
Get:8 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf libcurl3 armhf 7.52.1-5+deb9u5 [261 kB]
Get:15 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armhf azure-iot-sdk-c-lib armhf 0.1.0-54vivid [191 kB]
Get:9 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf libcurl4-openssl-dev armhf 7.52.1-5+deb9u5 [327 kB]
Get:10 http://mirror.freedif.org/Raspbian/raspbian stretch/main armhf libssl-doc all 1.1.0f-3+deb9u2 [1,459 kB]
Get:16 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid/main armhf azure-iot-sdk-c-dev armhf 0.1.0-54vivid [47.3 kB]
Fetched 5,389 kB in 1min 32s (58.2 kB/s)
apt-listchanges: Reading changelogs...
Preconfiguring packages ...
(Reading database ... 125194 files and directories currently installed.)
Preparing to unpack .../libuuid1_2.29.2-1+deb9u1_armhf.deb ...
Unpacking libuuid1:armhf (2.29.2-1+deb9u1) over (2.29.2-1) ...
Setting up libuuid1:armhf (2.29.2-1+deb9u1) ...
(Reading database ... 125194 files and directories currently installed.)
Preparing to unpack .../00-libssl1.1_1.1.0f-3+deb9u2_armhf.deb ...
Unpacking libssl1.1:armhf (1.1.0f-3+deb9u2) over (1.1.0f-3+deb9u1) ...
Selecting previously unselected package uuid-dev:armhf.
Preparing to unpack .../01-uuid-dev_2.29.2-1+deb9u1_armhf.deb ...
Unpacking uuid-dev:armhf (2.29.2-1+deb9u1) ...
Selecting previously unselected package libssl-dev:armhf.
Preparing to unpack .../02-libssl-dev_1.1.0f-3+deb9u2_armhf.deb ...
Unpacking libssl-dev:armhf (1.1.0f-3+deb9u2) ...
Preparing to unpack .../03-curl_7.52.1-5+deb9u5_armhf.deb ...
Unpacking curl (7.52.1-5+deb9u5) over (7.52.1-5+deb9u2) ...
Preparing to unpack .../04-libcurl3_7.52.1-5+deb9u5_armhf.deb ...
Unpacking libcurl3:armhf (7.52.1-5+deb9u5) over (7.52.1-5+deb9u2) ...
Selecting previously unselected package libcurl4-openssl-dev:armhf.
Preparing to unpack .../05-libcurl4-openssl-dev_7.52.1-5+deb9u5_armhf.deb ...
Unpacking libcurl4-openssl-dev:armhf (7.52.1-5+deb9u5) ...
Selecting previously unselected package azure-c-shared-util-lib.
Preparing to unpack .../06-azure-c-shared-util-lib_0.1.0-53vivid_armhf.deb ...
Unpacking azure-c-shared-util-lib (0.1.0-53vivid) ...
Selecting previously unselected package azure-c-shared-util-dev.
Preparing to unpack .../07-azure-c-shared-util-dev_0.1.0-53vivid_armhf.deb ...
Unpacking azure-c-shared-util-dev (0.1.0-53vivid) ...
Selecting previously unselected package azure-uamqp-c-lib.
Preparing to unpack .../08-azure-uamqp-c-lib_0.1.0-58vivid_armhf.deb ...
Unpacking azure-uamqp-c-lib (0.1.0-58vivid) ...
Selecting previously unselected package azure-uamqp-c-dev.
Preparing to unpack .../09-azure-uamqp-c-dev_0.1.0-58vivid_armhf.deb ...
Unpacking azure-uamqp-c-dev (0.1.0-58vivid) ...
Selecting previously unselected package azure-umqtt-c-lib.
Preparing to unpack .../10-azure-umqtt-c-lib_0.1.0-48vivid_armhf.deb ...
Unpacking azure-umqtt-c-lib (0.1.0-48vivid) ...
Selecting previously unselected package azure-umqtt-c-dev.
Preparing to unpack .../11-azure-umqtt-c-dev_0.1.0-48vivid_armhf.deb ...
Unpacking azure-umqtt-c-dev (0.1.0-48vivid) ...
Selecting previously unselected package azure-iot-sdk-c-lib.
Preparing to unpack .../12-azure-iot-sdk-c-lib_0.1.0-54vivid_armhf.deb ...
Unpacking azure-iot-sdk-c-lib (0.1.0-54vivid) ...
Selecting previously unselected package azure-iot-sdk-c-dev.
Preparing to unpack .../13-azure-iot-sdk-c-dev_0.1.0-54vivid_armhf.deb ...
Unpacking azure-iot-sdk-c-dev (0.1.0-54vivid) ...
Selecting previously unselected package libssl-doc.
Preparing to unpack .../14-libssl-doc_1.1.0f-3+deb9u2_all.deb ...
Unpacking libssl-doc (1.1.0f-3+deb9u2) ...
Setting up libcurl3:armhf (7.52.1-5+deb9u5) ...
Setting up uuid-dev:armhf (2.29.2-1+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Setting up libssl1.1:armhf (1.1.0f-3+deb9u2) ...
Setting up azure-umqtt-c-lib (0.1.0-48vivid) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libssl-doc (1.1.0f-3+deb9u2) ...
Setting up libcurl4-openssl-dev:armhf (7.52.1-5+deb9u5) ...
Setting up azure-umqtt-c-dev (0.1.0-48vivid) ...
Setting up curl (7.52.1-5+deb9u5) ...
Setting up libssl-dev:armhf (1.1.0f-3+deb9u2) ...
Setting up azure-c-shared-util-lib (0.1.0-53vivid) ...
Setting up azure-c-shared-util-dev (0.1.0-53vivid) ...
Setting up azure-uamqp-c-lib (0.1.0-58vivid) ...
Setting up azure-uamqp-c-dev (0.1.0-58vivid) ...
Setting up azure-iot-sdk-c-lib (0.1.0-54vivid) ...
Setting up azure-iot-sdk-c-dev (0.1.0-54vivid) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
pi@raspberrypi:~ $ git clone https://github.com/Azure-Samples/iot-hub-c-raspberrypi-client-app
Cloning into 'iot-hub-c-raspberrypi-client-app'...
remote: Counting objects: 97, done.
remote: Total 97 (delta 0), reused 0 (delta 0), pack-reused 97
Unpacking objects: 100% (97/97), done.
pi@raspberrypi:~ $ cd ./iot-hub-c-raspberrypi-client-app/
pi@raspberrypi:~/iot-hub-c-raspberrypi-client-app $ nano config.h
pi@raspberrypi:~/iot-hub-c-raspberrypi-client-app $ cmake . && make
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/iot-hub-c-raspberrypi-client-app
Scanning dependencies of target app
[ 20%] Building C object CMakeFiles/app.dir/main.c.o
/home/pi/iot-hub-c-raspberrypi-client-app/main.c:9:45: fatal error: azure_c_shared_utility/xlogging.h: No such file or directory
 #include <azure_c_shared_utility/xlogging.h>
                                             ^
compilation terminated.
CMakeFiles/app.dir/build.make:62: recipe for target 'CMakeFiles/app.dir/main.c.o' failed
make[2]: *** [CMakeFiles/app.dir/main.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/app.dir/all' failed
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

`

**Comment by lakshmisivareddy** [comment]
Hi @ninhvuonglinh-linhnv  i fixed the problem & below are the steps i followed 

1. my /usr/local/lib snap short
check all the libraries are present in your /usr/local/lib if not copy libraries from
location /home/pi/Source/azure-iot-sdk-c/cmake/iotsdk_linux
-rw-r--r-- 1 root staff 373338 May 23 10:26 libaziotsharedutil.a
-rw-r--r-- 1 root staff 236826 May 24 06:02 libiothub_client.a
-rw-r--r-- 1 root staff 367726 May 24 06:00 libiothub_client_amqp_transport.a
-rw-r--r-- 1 root staff 369180 May 24 05:58 libiothub_client_amqp_ws_transport.a
-rw-r--r-- 1 root staff 73186 May 24 06:01 libiothub_client_http_transport.a
-rw-r--r-- 1 root staff 92382 May 24 05:56 libiothub_client_mqtt_transport.a
-rw-r--r-- 1 root staff 92912 May 24 06:01 libiothub_client_mqtt_ws_transport.a
-rw-r--r-- 1 root staff 141008 May 24 05:55 libiothub_service_client.a
-rw-r--r-- 1 root staff 43368 May 24 05:50 libparson.a
-rw-r--r-- 1 root staff 260786 May 24 06:03 libserializer.a
-rw-r--r-- 1 root staff 47620 May 23 10:24 libumqtt.a
lrwxrwxrwx 1 root staff 22 May 24 06:06 libwiringPiDev.so -> libwiringPiDev.so.2.46
-rwxr-xr-x 1 root staff 28188 May 24 06:06 libwiringPiDev.so.2.46
lrwxrwxrwx 1 root staff 19 May 24 06:06 libwiringPi.so -> libwiringPi.so.2.46
-rwxr-xr-x 1 root staff 70184 May 24 06:06 libwiringPi.so.2.46
drwxrwsr-x 3 root staff 4096 Apr 18 00:52 pypy2.7
drwxrwsr-x 4 root staff 4096 Apr 18 00:26 python2.7
drwxrwsr-x 3 root staff 4096 Apr 18 00:18 python3.5

2. i copied internal folder from /home/pi/Source/azure-iot-sdk-c/iothub_client/inc to /usr/local/include/azureiot

3. in /home/pi/Source/azure-iot-sdk-c/iothub_client/CMakeLists.txt file
set(iothub_client_c_files
./src/iothub_client.c
./src/iothub_client_core.c
./src/iothub_client_core_ll.c
./src/iothub_client_diagnostic.c
./src/iothub_client_ll.c
./src/iothub_device_client.c
./src/iothub_device_client_ll.c
./src/iothub_message.c
./src/iothubtransport.c
./src/version.c
../deps/parson/parson.c

)
set(iothub_client_h_files
./inc/iothub_client_core.h
./inc/iothub_client_core_ll.h
./inc/iothub_client.h
./inc/internal/iothub_client_common.h
./inc/iothub_client_ll.h
./inc/internal/iothub_client_diagnostic.h
./inc/iothub_client_options.h
./inc/internal/iothub_client_private.h
./inc/iothub_client_version.h
./inc/iothub_device_client.h
./inc/iothub_device_client_ll.h
./inc/iothub_transport_ll.h
./inc/iothub_message.h
./inc/internal/iothubtransport.h
../deps/parson/parson.h
)

i added parson.h & parson.c files
