### ISSUE TITLE
Auto provisioning using esp32

### ISSUE THREAD

**Issue by naznaaa** [Azure/azure-iot-device-ecosystem#428]
Hi,
we have to register many device in the iot-hub so hard coding the connection string for each device is very difficult,instead of this can we have the code to recieve the connection string?or alternatively using DPS we can get the ID scope and global_prov_uri,it can be hard coded in the code since it is same for all device, but X.509 certificate is different for each device then how can we write the code in such a way that we can recieve the certificate.is it possible?
please give reply soon

Thanks

**Comment by SynapIoT** [comment]
Hi Naznaaa,
Did you ever get an answer to this question from MS?

**Comment by naznaaa** [comment]
Hi,
No reply  from MS. We have to connect esp32 and azure it hub using x.509
authentication, thereafter a direct communication between device and cloud
that is our requirement. Can you please help us with a sample code or a
document.

**Comment by DesarrolloMM** [comment]
Hi, im in the same need, have anyone get to a solution?

**Comment by rido-min** [comment]
@naznaa https://github.com/espressif/esp-azure/tree/master/examples/prov_dev_client_ll_sample provides sample code.

**Comment by thilojaeggi** [comment]
But doesn't that also require a different cert for each device?

**Comment by rido-min** [comment]
yes, each device requires a different certificate, ideally stored in the HSM. See https://docs.microsoft.com/en-us/azure/iot-dps/concepts-tpm-attestation for more information

**Comment by thilojaeggi** [comment]
So not really complete auto provisioning?

**Comment by rido-min** [comment]
not sure what are your expectations for auto-provisioning. When using X509 certificates, once the CA is configured in DPS, you can provision new devices by using any certificated issued by the CA.

**Comment by thilojaeggi** [comment]
But is there any possibility not to have anything in the code for each device?

**Comment by rido-min** [comment]
you don't need to have custom code for each device. Just ask the HSM for the certificate (that must be unique for each device).

**Comment by thilojaeggi** [comment]
Which afaik doesn't exist for the ESP32 but I think there's something similar. Thanks!
